apiVersion: v1
kind: Service
metadata:
  name: kritis-validation-hook
  labels:
    app: kritis-validation-hook
#    chart: {{ template "kritis.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}
#    {{ .Values.kritisInstallLabel }}: ""
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: kritis-validation-hook
#    release: {{ .Release.Name }}
