apiVersion: v1
kind: Pod
metadata:
  name: java
spec:
  containers:
    - name: java
#      image: gcr.azk8s.cn/kritis-tutorial/java-with-vulnz:latest
      image: gcr.azk8s.cn/kritis-tutorial/java-with-vulnz@sha256:358687cfd3ec8e1dfeb2bf51b5110e4e16f6df71f64fba01986f720b2fcba68a
      ports:
        - containerPort: 80
